// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://elnzbfvdlkessfzraufu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbnpiZnZkbGtlc3NmenJhdWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5ODg0NjgsImV4cCI6MjA3NjU2NDQ2OH0.rgP0Zkzz-HsJ8z5DriLxe2Hod4WG8Z0C3EMmc06_uV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);